---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cf-google-auth
  name: cf-google-auth
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 5555
  selector:
    app: cf-google-auth
